include:
  - ../db-persona/compose.yaml

services:
  api-persona:
    build: .
    container_name: api-persona
    ports:
      - "${API_PORT}:${API_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT}/healthcheck" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 50s
    networks:
      - net-persona
    depends_on:
      - db-persona
networks:
  net-persona:
    driver: bridge
