import { IOrganisationTypeControllerDeleteOrganisationTypeOutputError } from './IOrganisationTypeControllerDeleteOrganisationTypeOutputError';
import { IOrganisationTypeControllerDeleteOrganisationTypeOutputSuccess } from './IOrganisationTypeControllerDeleteOrganisationTypeOutputSuccess';

export type IOrganisationTypeControllerDeleteOrganisationTypeOutput =
  | IOrganisationTypeControllerDeleteOrganisationTypeOutputSuccess
  | IOrganisationTypeControllerDeleteOrganisationTypeOutputError;
