import { IOrganisationControllerUpdateOrganisationOutputError } from './IOrganisationControllerUpdateOrganisationOutputError';
import { IOrganisationControllerUpdateOrganisationOutputSuccess } from './IOrganisationControllerUpdateOrganisationOutputSuccess';

export type IOrganisationControllerUpdateOrganisationOutput =
  | IOrganisationControllerUpdateOrganisationOutputSuccess
  | IOrganisationControllerUpdateOrganisationOutputError;
