import { IOrganisationRoleControllerUpdateOrganisationRoleOutputError } from './IOrganisationRoleControllerUpdateOrganisationRoleOutputError';
import { IOrganisationRoleControllerUpdateOrganisationRoleOutputSuccess } from './IOrganisationRoleControllerUpdateOrganisationRoleOutputSuccess';

export type IOrganisationRoleControllerUpdateOrganisationRoleOutput =
  | IOrganisationRoleControllerUpdateOrganisationRoleOutputSuccess
  | IOrganisationRoleControllerUpdateOrganisationRoleOutputError;
