import { IOrganisationRoleControllerCreateOrganisationRoleOutputError } from './IOrganisationRoleControllerCreateOrganisationRoleOutputError';
import { IOrganisationRoleControllerCreateOrganisationRoleOutputSuccess } from './IOrganisationRoleControllerCreateOrganisationRoleOutputSuccess';

export type IOrganisationRoleControllerCreateOrganisationRoleOutput =
  | IOrganisationRoleControllerCreateOrganisationRoleOutputSuccess
  | IOrganisationRoleControllerCreateOrganisationRoleOutputError;
