import { IOrganisationUserControllerUpdateOrganisationUserOutputError } from './IOrganisationUserControllerUpdateOrganisationUserOutputError';
import { IOrganisationUserControllerUpdateOrganisationUserOutputSuccess } from './IOrganisationUserControllerUpdateOrganisationUserOutputSuccess';

export type IOrganisationUserControllerUpdateOrganisationUserOutput =
  | IOrganisationUserControllerUpdateOrganisationUserOutputSuccess
  | IOrganisationUserControllerUpdateOrganisationUserOutputError;
